clsspring.application.name=backend

#database
spring.datasource.url=jdbc:postgresql://127.0.0.1:5432/Vmeet
spring.datasource.username=postgres
spring.datasource.password=password

#Hibernate properties
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.ddl-auto=create
spring.jpa.properties.hibernate.format_sql=true






















