clsspring.application.name=backend
spring.config.import=classpath:database.properties

#database
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

# Database
# spring.datasource.url=jdbc:postgresql://ep-soft-glade-atd0aqiv.c-9.us-east-1.aws.neon.tech/neondb?sslmode=require
# spring.datasource.username=neondb_owner
# spring.datasource.password=npg_0o8MuLEcpWGf

#Hibernate properties
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true

# Dev tools
spring.devtools.restart.enabled=false








